@startuml
class com.wyu4.snowberryjam.compiler.data.tasks.ThreadTask {
- BodyStack body
+ <<Create>> ThreadTask(JsonNode)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
+ BodyStack getBody()
}


interface com.wyu4.snowberryjam.compiler.data.tasks.interfaces.NamedTask {
~ ValueHolder getName()
}

class com.wyu4.snowberryjam.compiler.data.values.conditional.And {
+ <<Create>> And(JsonNode)
+ Boolean getState()
+ SourceId getId()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.tasks.WarnTask {
- ValueHolder message
+ <<Create>> WarnTask(JsonNode)
+ <<Create>> WarnTask(String)
+ <<Create>> WarnTask(ValueHolder)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
+ ValueHolder getValue()
}


class com.wyu4.snowberryjam.Start {
- {static} Logger logger
+ {static} void main(String[])
+ void start(Stage)
}


class com.wyu4.snowberryjam.compiler.data.values.iteration.WithUpdatedElement {
+ <<Create>> WithUpdatedElement(JsonNode)
+ Object getValue()
+ SourceId getId()
+ Class<?> getType()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.tasks.macros.InputMacro {
+ <<Create>> InputMacro(JsonNode)
+ <<Create>> InputMacro(ValueHolder)
+ void execute()
}

class com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ArithmeticValueViewer {
+ <<Create>> ArithmeticValueViewer(ArithmeticHolder)
}

class com.wyu4.snowberryjam.compiler.data.values.math.Minus {
+ <<Create>> Minus(JsonNode)
+ <<Create>> Minus(ValueHolder,ValueHolder)
+ Object getValue()
+ SourceId getId()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.tasks.ErrorTask {
- ValueHolder message
+ <<Create>> ErrorTask(JsonNode)
+ <<Create>> ErrorTask(String)
+ <<Create>> ErrorTask(ValueHolder)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
+ ValueHolder getValue()
}


class com.wyu4.snowberryjam.compiler.data.values.conditional.ConditionalHolder {
+ <<Create>> ConditionalHolder(JsonNode)
+ Boolean getState()
+ boolean bothTypesAre(Class<?>)
+ Object getValue()
+ Class<?> getType()
+ boolean notEmpty()
+ String toString()
}

interface com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ValuedTask {
~ ValueHolder getValue()
}

class com.wyu4.snowberryjam.compiler.data.tasks.macros.IncreaseMacro {
+ <<Create>> IncreaseMacro(JsonNode)
+ <<Create>> IncreaseMacro(ValueHolder,ValueHolder)
}

class com.wyu4.snowberryjam.compiler.data.values.conditional.SameType {
+ <<Create>> SameType(JsonNode)
+ Boolean getState()
+ SourceId getId()
+ String toString()
}

class com.wyu4.snowberryjam.gui.viewer.codeviewer.CodeViewer {
- StackPane loadingOverlay
- ScrollPane scrollPane
- StackViewer primaryStackViewer
+ <<Create>> CodeViewer()
- void flush()
+ void refresh()
}


class com.wyu4.snowberryjam.gui.viewer.codeviewer.DottedStackPane {
+ <<Create>> DottedStackPane(int)
}

class com.wyu4.snowberryjam.gui.viewer.codeviewer.LoadingOverlay {
+ <<Create>> LoadingOverlay()
}

class com.wyu4.snowberryjam.compiler.data.values.iteration.ArrayHolder {
- ValueHolder i
+ <<Create>> ArrayHolder(JsonNode)
+ ValueHolder getI()
# int getValidIndex()
+ Class<?> getType()
+ String toString()
}


class com.wyu4.snowberryjam.compiler.data.values.conditional.GreaterOrEqualTo {
+ <<Create>> GreaterOrEqualTo(JsonNode)
+ Boolean getState()
+ SourceId getId()
+ String toString()
}

abstract class com.wyu4.snowberryjam.gui.viewer.codeviewer.ColorDictionary {
- {static} Color BUILT_IN
- {static} Color MATH
- {static} Color IF_STATEMENT
- {static} Color MACRO
- {static} Color LOOP
- {static} Color DELAY
- {static} Color STORAGE
- {static} Color CONDITIONAL
- {static} Color THREADING
- {static} Color CONVERSION
- {static} Color IO
- {static} Color ITERATION
- {static} Color BLAND
+ {static} Color getColorFromId(SourceId)
}


interface com.wyu4.snowberryjam.compiler.data.values.builtin.BuiltInHolder {
}
class com.wyu4.snowberryjam.compiler.data.values.conversion.ParseNumber {
+ <<Create>> ParseNumber(JsonNode)
+ Object getValue()
+ SourceId getId()
+ Class<?> getType()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.values.builtin.RandomHolder {
+ Object getValue()
+ SourceId getId()
+ Class<?> getType()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.values.conditional.Or {
+ <<Create>> Or(JsonNode)
+ Boolean getState()
+ SourceId getId()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.values.conversion.ConversionHolder {
+ <<Create>> ConversionHolder(JsonNode)
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.values.math.Modulus {
+ <<Create>> Modulus(JsonNode)
+ Object getValue()
+ SourceId getId()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.values.conditional.Equals {
+ <<Create>> Equals(JsonNode)
+ Boolean getState()
+ SourceId getId()
+ String toString()
}

interface com.wyu4.snowberryjam.compiler.data.tasks.interfaces.BodiedTask {
~ BodyStack getBody()
}

class com.wyu4.snowberryjam.gui.viewer.codeviewer.tasks.StackViewer {
- AtomicReference<ExecutableTask[]> tasks
- ObservableList<Node> children
+ <<Create>> StackViewer()
+ <<Create>> StackViewer(boolean)
+ void loadStack(BodyStack)
+ void loadStack(ExecutableTask[])
+ void flush()
}


class com.wyu4.snowberryjam.compiler.data.tasks.WhileTask {
- ValueHolder condition
- BodyStack body
+ <<Create>> WhileTask(JsonNode)
+ <<Create>> WhileTask(ConditionalHolder,BodyStack)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
+ BodyStack getBody()
+ ValueHolder getValue()
}


class com.wyu4.snowberryjam.compiler.data.values.iteration.ElementAtIndex {
+ <<Create>> ElementAtIndex(JsonNode)
+ Object getValue()
+ SourceId getId()
+ String toString()
}

class com.wyu4.snowberryjam.gui.viewer.codeviewer.tasks.Insets {
}
interface com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ElseBodiedTask {
~ BodyStack getSecondaryBody()
}

class com.wyu4.snowberryjam.compiler.data.values.conditional.Not {
+ <<Create>> Not(JsonNode)
+ Object getValue()
+ SourceId getId()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.tasks.SetTask {
- ValueHolder name
- ValueHolder value
+ <<Create>> SetTask(JsonNode)
+ <<Create>> SetTask(ValueHolder,ValueHolder)
+ void execute()
+ SourceId getId()
# ValueHolder getNameValue()
+ Object feedback()
+ String toString()
+ ValueHolder getValue()
+ ValueHolder getName()
}


class com.wyu4.snowberryjam.compiler.data.tasks.WaitUntilTask {
- {static} Logger logger
- {static} int INTERVAL
- ValueHolder condition
+ <<Create>> WaitUntilTask(JsonNode)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
+ ValueHolder getValue()
}


class com.wyu4.snowberryjam.compiler.data.tasks.RepeatTask {
- ValueHolder repeats
- ValueHolder variableName
- BodyStack body
+ <<Create>> RepeatTask(JsonNode)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
+ BodyStack getBody()
+ ValueHolder getValue()
+ ValueHolder getName()
}


class com.wyu4.snowberryjam.gui.framework.Interactor {
- {static} Logger logger
- Model model
- Stage stage
+ <<Create>> Interactor(Model,Stage)
+ Runnable createOpenFileTask()
+ Runnable createSetFileTask(File)
+ Runnable createSaveFileTask()
+ Runnable createSaveFileTask(File)
+ Runnable createSaveAsFileTask()
+ Runnable createNewProjectTask()
+ Runnable createCompileTask()
+ Runnable createCompileTask(Runnable)
+ Runnable createRunTask()
+ Runnable createStopTask()
+ Runnable createFormatCodeTask()
}


class com.wyu4.snowberryjam.compiler.data.values.math.ArithmeticHolder {
+ <<Create>> ArithmeticHolder(JsonNode)
+ <<Create>> ArithmeticHolder(ValueHolder,ValueHolder)
+ Object getValue()
+ boolean notEmpty()
+ String toString()
}

class com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ValueViewer {
+ {static} Color BORDER_COLOR
+ {static} CornerRadii SQUARE_RADII
+ {static} CornerRadii CIRCULAR_RADII
- ValueHolder value
+ <<Create>> ValueViewer(ValueHolder)
+ {static} Node buildValueViewer(ValueHolder)
+ ValueHolder getValue()
# void applyBorderWithRadii(CornerRadii)
}


interface com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask {
~ void execute()
~ SourceId getId()
~ Object feedback()
}

abstract class com.wyu4.snowberryjam.compiler.LocalStorage {
- {static} AtomicReference<Logger> logger
- {static} Logger inputLogger
- {static} HashMap<String,Object> VARIABLES
- {static} HashMap<String,Object> VARIABLES_COPY
- {static} List<Thread> THREADS
- {static} BodyStack STACK
- {static} AtomicReference<String> NAME
- {static} AtomicReference<String> DESCRIPTION
- {static} List<BiConsumer<String,String>> PRINT_LISTENERS
- {static} List<BiConsumer<String,String>> WARN_LISTENERS
- {static} List<BiConsumer<String,String>> ERROR_LISTENERS
- {static} List<Consumer<String>> INPUT_LISTENERS
- {static} HashMap<String,Consumer<Object>> VARIABLE_LISTENERS
- {static} AtomicInteger pointer
- {static} AtomicBoolean running
- {static} AtomicBoolean manualStop
+ {static} String getDefaultSource()
+ {static} Object getRaw(String)
+ {static} Set<String> getVariableNames()
+ {static} ExecutableTask[] copyStack()
+ {static} void flush()
+ {static} Thread createThread(Runnable)
+ {static} void setVariable(String,Object)
+ {static} void runStack()
+ {static} void stopRun()
+ {static} boolean isRunning()
# {static} void setName(String)
# {static} void setDescription(String)
# {static} void createVariable(String,Object)
# {static} void stackAdd(ExecutableTask)
+ {static} void increasePointer()
+ {static} int getPointer()
- {static} void resetPointer()
- {static} Logger getLogger()
+ {static} void sendInput(String)
+ {static} void print(Object,Object)
+ {static} void warn(Object,Object)
+ {static} void error(Object)
+ {static} void error(Object,Exception)
# {static} String formatMessage(Object,Object)
+ {static} void addPrintListener(BiConsumer<String,String>)
+ {static} void addWarnListener(BiConsumer<String,String>)
+ {static} void addErrorListener(BiConsumer<String,String>)
+ {static} void addVariableListener(String,Consumer<Object>)
+ {static} void addInputSubscription(Consumer<String>)
}


class com.wyu4.snowberryjam.compiler.data.values.math.Multiply {
+ <<Create>> Multiply(JsonNode)
+ Object getValue()
+ SourceId getId()
+ String toString()
}

class com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ConditionalValueViewer {
+ <<Create>> ConditionalValueViewer(ConditionalHolder)
}

class com.wyu4.snowberryjam.compiler.data.BodyStack {
- {static} Logger logger
- {static} AtomicBoolean DEBUGGING_ENABLED
- SourceId id
- List<ExecutableTask> stack
+ <<Create>> BodyStack(SourceId)
+ {static} void setDebuggingEnabled(boolean)
+ void addTask(ExecutableTask)
+ ExecutableTask[] copyStack()
+ void flush()
+ void execute()
+ Object feedback()
+ SourceId getId()
}


class com.wyu4.snowberryjam.compiler.data.tasks.macros.DecreaseMacro {
+ <<Create>> DecreaseMacro(JsonNode)
+ <<Create>> DecreaseMacro(ValueHolder,ValueHolder)
}

class com.wyu4.snowberryjam.compiler.data.values.conversion.SplitToArray {
+ <<Create>> SplitToArray(JsonNode)
+ Object getValue()
+ SourceId getId()
+ Class<?> getType()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.values.conversion.SizeOf {
+ <<Create>> SizeOf(JsonNode)
+ Object getValue()
+ SourceId getId()
+ Class<?> getType()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.values.math.Divide {
+ <<Create>> Divide(JsonNode)
+ Object getValue()
+ SourceId getId()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.tasks.WaitTask {
- {static} Logger logger
- {static} int INTERVAL
- ValueHolder time
+ <<Create>> WaitTask(JsonNode)
+ void execute()
+ SourceId getId()
+ Object feedback()
- long getTime()
+ String toString()
+ ValueHolder getValue()
}


class com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ConversionValueViewer {
+ <<Create>> ConversionValueViewer(ConversionHolder)
}

interface com.wyu4.snowberryjam.gui.viewer.Viewer {
~ void refresh()
}

class com.wyu4.snowberryjam.compiler.data.values.io.ReadFile {
+ <<Create>> ReadFile(JsonNode)
+ <<Create>> ReadFile(ValueHolder)
+ Object getValue()
+ SourceId getId()
+ Class<?> getType()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.values.VariableReference {
- ValueHolder name
+ <<Create>> VariableReference(String)
+ <<Create>> VariableReference(ValueHolder)
+ ValueHolder getName()
+ Object getValue()
+ SourceId getId()
+ String toString()
}


class com.wyu4.snowberryjam.compiler.data.values.math.Plus {
+ <<Create>> Plus(JsonNode)
+ <<Create>> Plus(ValueHolder,ValueHolder)
+ Object getValue()
+ SourceId getId()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.values.ValueHolder {
- Object value
+ <<Create>> ValueHolder()
+ <<Create>> ValueHolder(Object)
- {static} boolean isPrimitive(JsonNode)
+ {static} ValueHolder fromNode(JsonNode)
+ {static} ValueHolder checkValueIsConditional(ValueHolder)
+ Object getValue()
+ Object getPointer()
+ Object[] getArray()
+ String getString()
+ Class<?> getType()
+ boolean isType(Class<?>)
+ boolean notEmpty()
+ Double getSize()
+ SourceId getId()
+ boolean equals(Object)
+ boolean superEquals(Object)
+ String toString()
}


class com.wyu4.snowberryjam.compiler.data.values.builtin.TimeHolder {
+ Object getValue()
+ SourceId getId()
+ Class<?> getType()
+ String toString()
}

class com.wyu4.snowberryjam.gui.viewer.codeviewer.values.BuiltInViewer {
+ <<Create>> BuiltInViewer(ValueHolder)
}

class com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ArrayValueViewer {
+ <<Create>> ArrayValueViewer(ArrayHolder)
}

class com.wyu4.snowberryjam.gui.framework.Controller {
- Builder<Region> builder
- Model model
- Interactor interactor
+ <<Create>> Controller(Stage)
+ void updateFile(File)
+ File getSourceFile()
+ ObjectProperty<File> getSourceFileProperty()
+ Region getView()
}


class com.wyu4.snowberryjam.compiler.data.tasks.IfElseTask {
- ValueHolder condition
- BodyStack body
- BodyStack elseBody
+ <<Create>> IfElseTask(JsonNode)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
+ BodyStack getBody()
+ BodyStack getSecondaryBody()
+ ValueHolder getValue()
}


abstract class com.wyu4.snowberryjam.compiler.Compiler {
- {static} Logger logger
- {static} List<BiConsumer<String,String>> PRINT_LISTENERS
- {static} List<BiConsumer<String,String>> WARN_LISTENERS
- {static} List<BiConsumer<String,String>> ERROR_LISTENERS
+ {static} String formatString(String)
- {static} JsonNode getTree(String)
+ {static} void compile(String)
- {static} void mapProjectData(JsonNode)
- {static} void mapProjectVariables(JsonNode)
- {static} void compileEvents(JsonNode)
+ {static} void compileBody(JsonNode,BodyStack)
- {static} String getProperty(JsonNode,String)
+ {static} String getId(JsonNode)
+ {static} String getName(JsonNode)
+ {static} Object asPrimitiveObject(JsonNode)
+ {static} void print(Object,Object)
+ {static} void printTab(Object,Object)
+ {static} void error(Object)
+ {static} void error(Object,Exception)
+ {static} void warn(Object,Object)
+ {static} void addPrintListener(BiConsumer<String,String>)
+ {static} void addWarnListener(BiConsumer<String,String>)
+ {static} void addErrorListener(BiConsumer<String,String>)
}


class com.wyu4.snowberryjam.gui.viewer.codeviewer.values.VariableReferenceViewer {
+ <<Create>> VariableReferenceViewer(VariableReference)
}

class com.wyu4.snowberryjam.gui.framework.Model {
- ObjectProperty<File> sourceFileProperty
- ObjectProperty<Page> pageProperty
- BooleanProperty saveDisabledProperty
- BooleanProperty saveAsDisabledProperty
- BooleanProperty runDisabledProperty
- BooleanProperty compilingProperty
- BooleanProperty runningProperty
- StringProperty sourceCodeProperty
- StringProperty builtSourceCodeProperty
+ <<Create>> Model()
+ ObjectProperty<File> getSourceFileProperty()
+ ObjectProperty<Page> getPageProperty()
+ BooleanProperty getSaveDisabledProperty()
+ BooleanProperty getSaveAsDisabledProperty()
+ BooleanProperty getRunDisabledProperty()
+ BooleanProperty getCompilingProperty()
+ BooleanProperty getRunningProperty()
+ StringProperty getSourceCodeProperty()
+ StringProperty getBuiltSourceCodeProperty()
+ File getSourceFile()
+ Page getPage()
+ boolean getSaveDisabled()
+ boolean getSaveAsDisabled()
+ boolean getRunDisabled()
+ boolean getCompiling()
+ boolean getRunning()
+ String getSourceCode()
+ String getBuiltSourceCode()
}


enum com.wyu4.snowberryjam.gui.framework.Page {
+  EDITOR
+  VIEWER
}

enum com.wyu4.snowberryjam.compiler.enums.SourceKey {
+  ARRAY
+  BODY
+  ELSE
+  EVENTS
+  ID
+  NAME
+  PARAM_A
+  PARAM_B
+  PARAM_I
+  VARIABLES
+  VALUE
- String key
~ <<Create>> SourceKey(String)
+ String toString()
}


class com.wyu4.snowberryjam.compiler.data.values.conditional.LessOrEqualTo {
+ <<Create>> LessOrEqualTo(JsonNode)
+ Boolean getState()
+ SourceId getId()
+ String toString()
}

abstract class com.wyu4.snowberryjam.ResourceUtils {
- {static} Logger logger
+ {static} String IMAGES
+ {static} String PUBLIC
+ {static} String getFullPath(ResourceFile)
+ {static} URL getFullPathAsUrl(ResourceFile)
+ {static} String readFile(ResourceFile)
+ {static} String readFile(File)
+ {static} void createPublicFile()
}


enum com.wyu4.snowberryjam.ResourceFile {
+  COMPILER_ICON
+  DEFAULT_SOURCE
+  IMAGES_FOLDER
+  STYLE
- String path
~ <<Create>> ResourceFile(String)
+ String toString()
}


abstract class com.wyu4.snowberryjam.gui.editorutils.AutoComplete {
+ {static} void persistIndent(CodeArea)
+ {static} void formatIndent(CodeArea)
+ {static} void fullfillPunctation(CodeArea)
+ {static} void replaceBefore(CodeArea,Object,int)
+ {static} void replace(CodeArea,Object,int,int)
+ {static} void insertBefore(CodeArea,Object,int)
+ {static} void insertAfter(CodeArea,Object,int)
}

class com.wyu4.snowberryjam.gui.viewer.VariableViewer {
- TableColumn<VariableListener,String> nameColumn
- TableColumn<VariableListener,String> typeColumn
- TableColumn<VariableListener,String> valueColumn
- ObservableList<VariableListener> variables
+ <<Create>> VariableViewer()
+ void refresh()
}


class com.wyu4.snowberryjam.gui.viewer.VariableListener {
- StringProperty name
- StringProperty type
- ObjectProperty<Object> value
+ <<Create>> VariableListener(String)
+ ObjectProperty<Object> getValueProperty()
+ StringProperty getTypeProperty()
+ StringProperty getNameProperty()
}


class com.wyu4.snowberryjam.compiler.data.values.builtin.InputHolder {
- AtomicInteger currentPointer
- AtomicReference<String> input
+ Object getValue()
+ SourceId getId()
+ Class<?> getType()
+ String toString()
}


class com.wyu4.snowberryjam.compiler.data.values.conditional.GreaterThan {
+ <<Create>> GreaterThan(JsonNode)
+ Boolean getState()
+ SourceId getId()
+ String toString()
}

enum com.wyu4.snowberryjam.compiler.enums.SourceId {
+  AND
+  ARRAY_OF
+  ELEMENT_AT_INDEX
+  ERROR
+  DECREASE_MACRO
+  DIVIDE
+  EQUALS
+  GREATER_THAN
+  GREATER_OR_EQUAL_TO
+  IF
+  IF_ELSE
+  INCREASE_MACRO
+  INPUT
+  INPUT_MACRO
+  LESS_THAN
+  LESS_OR_EQUAL_TO
+  ON_RUN
+  OR
+  MINUS
+  MODULUS
+  MULTIPLY
+  NOT
+  NOT_EQUALS
+  PARSE_NUMBER
+  PLUS
+  PRINT
+  PROJECT
+  PUBLIC_FOLDER
+  RANDOM
+  READ_FILE
+  REPEAT
+  ROUND
+  SAME_TYPE
+  SET
+  SIZE_OF
+  SPLIT
+  THREAD
+  TIME
+  VARIABLE
+  WAIT
+  WAIT_UNTIL
+  WARN
+  WHILE
+  WITH_UPDATED_ELEMENT
- String id
- String beautified
~ <<Create>> SourceId(String)
~ <<Create>> SourceId(String,String)
+ String getBeautified()
+ String toString()
}


class com.wyu4.snowberryjam.compiler.data.values.builtin.PublicFolderHolder {
+ Object getValue()
+ SourceId getId()
+ Class<?> getType()
+ String toString()
}

abstract class com.wyu4.snowberryjam.compiler.enums.EnumHelper {
+ {static} SourceId stringToId(String)
+ {static} SourceKey stringToKey(String)
}

class com.wyu4.snowberryjam.compiler.data.values.InteractiveValueHolder {
- ValueHolder a
- ValueHolder b
+ <<Create>> InteractiveValueHolder(JsonNode)
+ <<Create>> InteractiveValueHolder(ValueHolder,ValueHolder)
+ ValueHolder getA()
+ ValueHolder getB()
}


class com.wyu4.snowberryjam.compiler.data.tasks.IfTask {
- ValueHolder condition
- BodyStack body
+ <<Create>> IfTask(JsonNode)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
+ BodyStack getBody()
+ ValueHolder getValue()
}


class com.wyu4.snowberryjam.gui.viewer.codeviewer.tasks.TaskViewer {
- {static} CornerRadii corner
- ExecutableTask task
- SourceId id
- HBox titleHBox
- HBox bottomHBox
- Node nameProperty
- Node valueProperty
- VBox innerContent
- StackViewer bodyViewer
- StackViewer secondaryBodyViewer
+ <<Create>> TaskViewer(ExecutableTask)
+ void load()
- VBox getInnerContent()
- HBox getBottomHBox()
- void addNameProperty(ValueHolder)
- void addValueProperty(ValueHolder)
- StackViewer getBodyViewer()
- StackViewer getSecondaryBodyViewer()
}


class com.wyu4.snowberryjam.compiler.data.values.conversion.ArrayOf {
+ <<Create>> ArrayOf(JsonNode)
+ Object getValue()
+ SourceId getId()
+ Class<?> getType()
+ String toString()
}

class com.wyu4.snowberryjam.gui.framework.ViewBuilder {
- {static} Logger logger
- Model model
- Interactor interactor
+ <<Create>> ViewBuilder(Model,Interactor)
+ Region build()
+ Node createMenuBar()
+ Node createProjectWidget()
+ Node createConsole()
+ Node createLog(String,String,Color)
+ Node createProjectViewer()
+ Node createCodeEditor()
}


class com.wyu4.snowberryjam.compiler.data.values.conditional.NotEquals {
+ <<Create>> NotEquals(JsonNode)
+ Boolean getState()
+ SourceId getId()
+ String toString()
}

class com.wyu4.snowberryjam.compiler.data.values.conditional.LessThan {
+ <<Create>> LessThan(JsonNode)
+ Boolean getState()
+ SourceId getId()
+ String toString()
}

abstract class com.wyu4.snowberryjam.gui.editorutils.Filter {
+ {static} boolean isSpecialOperation(KeyEvent)
+ {static} boolean isWrappablePunctuation(KeyEvent)
}

class com.wyu4.snowberryjam.compiler.data.tasks.PrintTask {
- ValueHolder message
+ <<Create>> PrintTask(JsonNode)
+ <<Create>> PrintTask(String)
+ <<Create>> PrintTask(ValueHolder)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
+ ValueHolder getValue()
}


class com.wyu4.snowberryjam.compiler.data.values.math.Round {
+ <<Create>> Round(JsonNode)
+ Object getValue()
+ SourceId getId()
+ String toString()
}

class com.wyu4.snowberryjam.gui.viewer.codeviewer.values.PrimitiveValueViewer {
+ <<Create>> PrimitiveValueViewer(ValueHolder)
}



com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.ThreadTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.BodiedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.ThreadTask
com.wyu4.snowberryjam.compiler.data.values.conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conditional.And
com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.WarnTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ValuedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.WarnTask
javafx.application.Application <|-- com.wyu4.snowberryjam.Start
com.wyu4.snowberryjam.compiler.data.values.iteration.ArrayHolder <|-- com.wyu4.snowberryjam.compiler.data.values.iteration.WithUpdatedElement
com.wyu4.snowberryjam.compiler.data.tasks.SetTask <|-- com.wyu4.snowberryjam.compiler.data.tasks.macros.InputMacro
javafx.scene.layout.StackPane <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ArithmeticValueViewer
com.wyu4.snowberryjam.compiler.data.values.math.ArithmeticHolder <|-- com.wyu4.snowberryjam.compiler.data.values.math.Minus
com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.ErrorTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ValuedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.ErrorTask
com.wyu4.snowberryjam.compiler.data.values.InteractiveValueHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conditional.ConditionalHolder
com.wyu4.snowberryjam.compiler.data.tasks.SetTask <|-- com.wyu4.snowberryjam.compiler.data.tasks.macros.IncreaseMacro
com.wyu4.snowberryjam.compiler.data.values.conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conditional.SameType
com.wyu4.snowberryjam.gui.viewer.Viewer <|.. com.wyu4.snowberryjam.gui.viewer.codeviewer.CodeViewer
javafx.scene.layout.StackPane <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.CodeViewer
javafx.scene.layout.StackPane <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.DottedStackPane
javafx.scene.layout.StackPane <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.LoadingOverlay
com.wyu4.snowberryjam.compiler.data.values.InteractiveValueHolder <|-- com.wyu4.snowberryjam.compiler.data.values.iteration.ArrayHolder
com.wyu4.snowberryjam.compiler.data.values.conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conditional.GreaterOrEqualTo
com.wyu4.snowberryjam.compiler.data.values.conversion.ConversionHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conversion.ParseNumber
com.wyu4.snowberryjam.compiler.data.values.builtin.BuiltInHolder <|.. com.wyu4.snowberryjam.compiler.data.values.builtin.RandomHolder
com.wyu4.snowberryjam.compiler.data.values.ValueHolder <|-- com.wyu4.snowberryjam.compiler.data.values.builtin.RandomHolder
com.wyu4.snowberryjam.compiler.data.values.conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conditional.Or
com.wyu4.snowberryjam.compiler.data.values.InteractiveValueHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conversion.ConversionHolder
com.wyu4.snowberryjam.compiler.data.values.math.ArithmeticHolder <|-- com.wyu4.snowberryjam.compiler.data.values.math.Modulus
com.wyu4.snowberryjam.compiler.data.values.conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conditional.Equals
javafx.scene.layout.VBox <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.tasks.StackViewer
com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.WhileTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.BodiedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.WhileTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ValuedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.WhileTask
com.wyu4.snowberryjam.compiler.data.values.iteration.ArrayHolder <|-- com.wyu4.snowberryjam.compiler.data.values.iteration.ElementAtIndex
com.wyu4.snowberryjam.compiler.data.values.conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conditional.Not
com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.SetTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ValuedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.SetTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.NamedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.SetTask
com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.WaitUntilTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ValuedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.WaitUntilTask
com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.RepeatTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.BodiedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.RepeatTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ValuedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.RepeatTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.NamedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.RepeatTask
com.wyu4.snowberryjam.compiler.data.values.InteractiveValueHolder <|-- com.wyu4.snowberryjam.compiler.data.values.math.ArithmeticHolder
javafx.scene.layout.HBox <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ValueViewer
com.wyu4.snowberryjam.compiler.data.values.math.ArithmeticHolder <|-- com.wyu4.snowberryjam.compiler.data.values.math.Multiply
com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ValueViewer <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ConditionalValueViewer
com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask <|.. com.wyu4.snowberryjam.compiler.data.BodyStack
com.wyu4.snowberryjam.compiler.data.tasks.SetTask <|-- com.wyu4.snowberryjam.compiler.data.tasks.macros.DecreaseMacro
com.wyu4.snowberryjam.compiler.data.values.conversion.ConversionHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conversion.SplitToArray
com.wyu4.snowberryjam.compiler.data.values.conversion.ConversionHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conversion.SizeOf
com.wyu4.snowberryjam.compiler.data.values.math.ArithmeticHolder <|-- com.wyu4.snowberryjam.compiler.data.values.math.Divide
com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.WaitTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ValuedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.WaitTask
javafx.scene.layout.StackPane <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ConversionValueViewer
com.wyu4.snowberryjam.compiler.data.values.InteractiveValueHolder <|-- com.wyu4.snowberryjam.compiler.data.values.io.ReadFile
com.wyu4.snowberryjam.compiler.data.values.ValueHolder <|-- com.wyu4.snowberryjam.compiler.data.values.VariableReference
com.wyu4.snowberryjam.compiler.data.values.math.ArithmeticHolder <|-- com.wyu4.snowberryjam.compiler.data.values.math.Plus
com.wyu4.snowberryjam.compiler.data.values.builtin.BuiltInHolder <|.. com.wyu4.snowberryjam.compiler.data.values.builtin.TimeHolder
com.wyu4.snowberryjam.compiler.data.values.ValueHolder <|-- com.wyu4.snowberryjam.compiler.data.values.builtin.TimeHolder
com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ValueViewer <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.values.BuiltInViewer
com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ValueViewer <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ArrayValueViewer
com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.IfElseTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.BodiedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.IfElseTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ElseBodiedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.IfElseTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ValuedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.IfElseTask
com.wyu4.snowberryjam.compiler.LocalStorage <|-- com.wyu4.snowberryjam.compiler.Compiler
com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ValueViewer <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.values.VariableReferenceViewer
com.wyu4.snowberryjam.compiler.data.values.conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conditional.LessOrEqualTo
com.wyu4.snowberryjam.gui.viewer.Viewer <|.. com.wyu4.snowberryjam.gui.viewer.VariableViewer
javafx.scene.control.TableView <|-- com.wyu4.snowberryjam.gui.viewer.VariableViewer
com.wyu4.snowberryjam.compiler.data.values.builtin.BuiltInHolder <|.. com.wyu4.snowberryjam.compiler.data.values.builtin.InputHolder
com.wyu4.snowberryjam.compiler.data.values.ValueHolder <|-- com.wyu4.snowberryjam.compiler.data.values.builtin.InputHolder
com.wyu4.snowberryjam.compiler.data.values.conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conditional.GreaterThan
com.wyu4.snowberryjam.compiler.data.values.builtin.BuiltInHolder <|.. com.wyu4.snowberryjam.compiler.data.values.builtin.PublicFolderHolder
com.wyu4.snowberryjam.compiler.data.values.ValueHolder <|-- com.wyu4.snowberryjam.compiler.data.values.builtin.PublicFolderHolder
com.wyu4.snowberryjam.compiler.data.values.ValueHolder <|-- com.wyu4.snowberryjam.compiler.data.values.InteractiveValueHolder
com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.IfTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.BodiedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.IfTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ValuedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.IfTask
javafx.scene.layout.VBox <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.tasks.TaskViewer
com.wyu4.snowberryjam.compiler.data.values.conversion.ConversionHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conversion.ArrayOf
javafx.util.Builder <|.. com.wyu4.snowberryjam.gui.framework.ViewBuilder
com.wyu4.snowberryjam.compiler.data.values.conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conditional.NotEquals
com.wyu4.snowberryjam.compiler.data.values.conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.compiler.data.values.conditional.LessThan
com.wyu4.snowberryjam.compiler.data.tasks.ExecutableTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.PrintTask
com.wyu4.snowberryjam.compiler.data.tasks.interfaces.ValuedTask <|.. com.wyu4.snowberryjam.compiler.data.tasks.PrintTask
com.wyu4.snowberryjam.compiler.data.values.math.ArithmeticHolder <|-- com.wyu4.snowberryjam.compiler.data.values.math.Round
com.wyu4.snowberryjam.gui.viewer.codeviewer.values.ValueViewer <|-- com.wyu4.snowberryjam.gui.viewer.codeviewer.values.PrimitiveValueViewer
@enduml