@startuml
interface com.wyu4.snowberryjam.Compiler.DataType.Tasks.ExecutableTask {
~ void execute()
~ SourceId getId()
~ Object feedback()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.Conversion.SizeOf {
+ <<Create>> SizeOf(JsonNode)
+ Object getValue()
+ Class<?> getType()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.GreaterOrEqualTo {
+ <<Create>> GreaterOrEqualTo(JsonNode)
+ Boolean getState()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.Math.Multiply {
+ <<Create>> Multiply(JsonNode)
+ Object getValue()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.Math.Plus {
+ <<Create>> Plus(JsonNode)
+ Object getValue()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Tasks.Repeat {
- ValueHolder condition
- BodyStack body
+ <<Create>> Repeat(JsonNode)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
}


class com.wyu4.snowberryjam.Compiler.DataType.Values.VariableReference {
- String name
+ <<Create>> VariableReference(String)
+ String getName()
+ Object getValue()
+ String toString()
}


class com.wyu4.snowberryjam.Compiler.DataType.Values.Array.ArrayHolder {
- ValueHolder i
+ <<Create>> ArrayHolder(JsonNode)
# ValueHolder getI()
# int getValidIndex()
+ String toString()
}


class com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.Or {
+ <<Create>> Or(JsonNode)
+ Boolean getState()
+ String toString()
}

class com.wyu4.snowberryjam.Framework.Controller {
- Builder<Region> builder
+ <<Create>> Controller()
+ Region getView()
}


class com.wyu4.snowberryjam.Framework.Model {
}
class com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.GreaterThan {
+ <<Create>> GreaterThan(JsonNode)
+ Boolean getState()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.Math.ArithmeticHolder {
+ <<Create>> ArithmeticHolder(JsonNode)
+ Object getValue()
+ boolean notEmpty()
+ String toString()
}

abstract class com.wyu4.snowberryjam.Compiler.Enums.EnumHelper {
+ {static} SourceId stringToId(String)
+ {static} SourceKey stringToKey(String)
}

abstract class com.wyu4.snowberryjam.Compiler.LocalStorage {
- {static} Logger logger
- {static} HashMap<String,Object> VARIABLES
- {static} List<Thread> THREADS
- {static} BodyStack STACK
- {static} AtomicReference<String> NAME
+ {static} Object getRaw(String)
+ {static} void flush()
+ {static} Thread createThread(Runnable)
+ {static} void setVariable(String,Object)
# {static} void runStack()
# {static} void setName(String)
# {static} void createVariable(String,Object)
# {static} void stackAdd(ExecutableTask)
- {static} Logger getLogger()
+ {static} void print(Object,Object)
+ {static} void warn(Object,Object)
}


class com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.SameType {
+ <<Create>> SameType(JsonNode)
+ Boolean getState()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.Conversion.ArrayOf {
+ <<Create>> ArrayOf(JsonNode)
+ Object getValue()
+ Class<?> getType()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.ValueHolder {
- Object value
+ <<Create>> ValueHolder()
+ <<Create>> ValueHolder(Object)
- {static} boolean isPrimitive(JsonNode)
+ {static} ValueHolder fromNode(JsonNode)
+ {static} ValueHolder checkValueIsConditional(ValueHolder)
+ Object getValue()
+ Object[] getArray()
+ String getString()
+ Class<?> getType()
+ boolean isType(Class<?>)
+ boolean notEmpty()
+ Double getSize()
+ boolean equals(Object)
+ String toString()
}


class com.wyu4.snowberryjam.Start {
- {static} Logger logger
+ {static} void main(String[])
+ void start(Stage)
}


enum com.wyu4.snowberryjam.Compiler.Enums.SourceId {
+  AND
+  ARRAY_OF
+  ELEMENT_AT_INDEX
+  DIVIDE
+  EQUALS
+  GREATER_THAN
+  GREATER_OR_EQUAL_TO
+  IF
+  IF_ELSE
+  LESS_THAN
+  LESS_OR_EQUAL_TO
+  ON_RUN
+  OR
+  MINUS
+  MODULUS
+  MULTIPLY
+  NOT
+  PLUS
+  PRINT
+  PROJECT
+  RANDOM
+  REPEAT
+  ROUND
+  SAME_TYPE
+  SET
+  WITH_UPDATED_ELEMENT
+  SIZE_OF
+  TIME
+  VARIABLE
+  WHILE
- String id
~ <<Create>> SourceId(String)
+ String toString()
}


class com.wyu4.snowberryjam.Compiler.CompilerTest {
+ {static} void test(File)
+ {static} void main(String[])
}

class com.wyu4.snowberryjam.Framework.ViewBuilder {
- {static} Logger logger
- Model model
+ <<Create>> ViewBuilder(Model)
+ Region build()
}


class com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.Not {
+ <<Create>> Not(JsonNode)
+ Object getValue()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Tasks.PrintTask {
- ValueHolder message
+ <<Create>> PrintTask(JsonNode)
+ <<Create>> PrintTask(ValueHolder)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
}


class com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.LessOrEqualTo {
+ <<Create>> LessOrEqualTo(JsonNode)
+ Boolean getState()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.BuiltIn.RandomHolder {
+ Object getValue()
+ Class<?> getType()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.Array.ElementAtIndex {
+ <<Create>> ElementAtIndex(JsonNode)
+ Object getValue()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.ConditionalHolder {
+ <<Create>> ConditionalHolder(JsonNode)
+ Boolean getState()
+ boolean bothTypesAre(Class<?>)
+ Object getValue()
+ Class<?> getType()
+ boolean notEmpty()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.Equals {
+ <<Create>> Equals(JsonNode)
+ Boolean getState()
+ String toString()
}

enum com.wyu4.snowberryjam.Compiler.Enums.SourceKey {
+  ARRAY
+  BODY
+  ELSE
+  EVENTS
+  ID
+  NAME
+  PARAM_A
+  PARAM_B
+  PARAM_I
+  VARIABLES
+  VALUE
- String key
~ <<Create>> SourceKey(String)
+ String toString()
}


class com.wyu4.snowberryjam.Compiler.DataType.Tasks.WhileTask {
- ValueHolder condition
- BodyStack body
+ <<Create>> WhileTask(JsonNode)
+ <<Create>> WhileTask(ConditionalHolder,BodyStack)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
}


class com.wyu4.snowberryjam.Compiler.DataType.Values.Math.Modulus {
+ <<Create>> Modulus(JsonNode)
+ Object getValue()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.Math.Divide {
+ <<Create>> Divide(JsonNode)
+ Object getValue()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Tasks.SetTask {
- ValueHolder name
- ValueHolder value
+ <<Create>> SetTask(JsonNode)
+ <<Create>> SetTask(ValueHolder,ValueHolder)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
}


class com.wyu4.snowberryjam.Compiler.DataType.Tasks.IfElseTask {
- ValueHolder condition
- BodyStack body
- BodyStack elseBody
+ <<Create>> IfElseTask(JsonNode)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
}


class com.wyu4.snowberryjam.Compiler.DataType.Values.InteractiveValueHolder {
- ValueHolder a
- ValueHolder b
+ <<Create>> InteractiveValueHolder(JsonNode)
+ <<Create>> InteractiveValueHolder(ValueHolder,ValueHolder)
# ValueHolder getA()
# ValueHolder getB()
}


class com.wyu4.snowberryjam.Compiler.DataType.Values.Math.Round {
+ <<Create>> Round(JsonNode)
+ Object getValue()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.Math.Minus {
+ <<Create>> Minus(JsonNode)
+ Object getValue()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.BuiltIn.TimeHolder {
+ Object getValue()
+ Class<?> getType()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.And {
+ <<Create>> And(JsonNode)
+ Boolean getState()
+ String toString()
}

abstract class com.wyu4.snowberryjam.Compiler.Compiler {
- {static} Logger logger
- {static} JsonNode getTree(String)
+ {static} void compile(String)
- {static} void mapProjectData(JsonNode)
- {static} void mapProjectVariables(JsonNode)
- {static} void compileEvents(JsonNode)
+ {static} void compileBody(JsonNode,BodyStack)
- {static} String getProperty(JsonNode,String)
+ {static} String getId(JsonNode)
+ {static} String getName(JsonNode)
+ {static} Object asPrimitiveObject(JsonNode)
+ {static} void print(Object,Object)
+ {static} void printTab(Object,Object)
+ {static} void error(Object)
+ {static} void error(Object,Exception)
+ {static} void warn(Object,Object)
}


class com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.LessThan {
+ <<Create>> LessThan(JsonNode)
+ Boolean getState()
+ String toString()
}

class com.wyu4.snowberryjam.Compiler.DataType.BodyStack {
- {static} Logger logger
- {static} AtomicBoolean DEBUGGING_ENABLED
- SourceId id
- List<ExecutableTask> stack
+ <<Create>> BodyStack(SourceId)
+ {static} void setDebuggingEnabled(boolean)
+ void addTask(ExecutableTask)
+ ExecutableTask[] copyStack()
+ void flush()
+ void execute()
+ Object feedback()
+ SourceId getId()
}


class com.wyu4.snowberryjam.Compiler.DataType.Values.Array.WithUpdatedElement {
+ <<Create>> WithUpdatedElement(JsonNode)
+ Object getValue()
+ Class<?> getType()
}

class com.wyu4.snowberryjam.Framework.Interactor {
- {static} Logger logger
- Model model
+ <<Create>> Interactor(Model)
}


class com.wyu4.snowberryjam.Compiler.DataType.Tasks.IfTask {
- ValueHolder condition
- BodyStack body
+ <<Create>> IfTask(JsonNode)
+ void execute()
+ SourceId getId()
+ Object feedback()
+ String toString()
}




com.wyu4.snowberryjam.Compiler.DataType.Values.InteractiveValueHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Conversion.SizeOf
com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.GreaterOrEqualTo
com.wyu4.snowberryjam.Compiler.DataType.Values.Math.ArithmeticHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Math.Multiply
com.wyu4.snowberryjam.Compiler.DataType.Values.Math.ArithmeticHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Math.Plus
com.wyu4.snowberryjam.Compiler.DataType.Tasks.ExecutableTask <|.. com.wyu4.snowberryjam.Compiler.DataType.Tasks.Repeat
com.wyu4.snowberryjam.Compiler.DataType.Values.ValueHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.VariableReference
com.wyu4.snowberryjam.Compiler.DataType.Values.InteractiveValueHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Array.ArrayHolder
com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.Or
com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.GreaterThan
com.wyu4.snowberryjam.Compiler.DataType.Values.InteractiveValueHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Math.ArithmeticHolder
com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.SameType
com.wyu4.snowberryjam.Compiler.DataType.Values.InteractiveValueHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Conversion.ArrayOf
javafx.application.Application <|-- com.wyu4.snowberryjam.Start
javafx.util.Builder <|.. com.wyu4.snowberryjam.Framework.ViewBuilder
com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.Not
com.wyu4.snowberryjam.Compiler.DataType.Tasks.ExecutableTask <|.. com.wyu4.snowberryjam.Compiler.DataType.Tasks.PrintTask
com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.LessOrEqualTo
com.wyu4.snowberryjam.Compiler.DataType.Values.ValueHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.BuiltIn.RandomHolder
com.wyu4.snowberryjam.Compiler.DataType.Values.Array.ArrayHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Array.ElementAtIndex
com.wyu4.snowberryjam.Compiler.DataType.Values.InteractiveValueHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.ConditionalHolder
com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.Equals
com.wyu4.snowberryjam.Compiler.DataType.Tasks.ExecutableTask <|.. com.wyu4.snowberryjam.Compiler.DataType.Tasks.WhileTask
com.wyu4.snowberryjam.Compiler.DataType.Values.Math.ArithmeticHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Math.Modulus
com.wyu4.snowberryjam.Compiler.DataType.Values.Math.ArithmeticHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Math.Divide
com.wyu4.snowberryjam.Compiler.DataType.Tasks.ExecutableTask <|.. com.wyu4.snowberryjam.Compiler.DataType.Tasks.SetTask
com.wyu4.snowberryjam.Compiler.DataType.Tasks.ExecutableTask <|.. com.wyu4.snowberryjam.Compiler.DataType.Tasks.IfElseTask
com.wyu4.snowberryjam.Compiler.DataType.Values.ValueHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.InteractiveValueHolder
com.wyu4.snowberryjam.Compiler.DataType.Values.Math.ArithmeticHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Math.Round
com.wyu4.snowberryjam.Compiler.DataType.Values.Math.ArithmeticHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Math.Minus
com.wyu4.snowberryjam.Compiler.DataType.Values.ValueHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.BuiltIn.TimeHolder
com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.And
com.wyu4.snowberryjam.Compiler.LocalStorage <|-- com.wyu4.snowberryjam.Compiler.Compiler
com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.ConditionalHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Conditional.LessThan
com.wyu4.snowberryjam.Compiler.DataType.Tasks.ExecutableTask <|.. com.wyu4.snowberryjam.Compiler.DataType.BodyStack
com.wyu4.snowberryjam.Compiler.DataType.Values.Array.ArrayHolder <|-- com.wyu4.snowberryjam.Compiler.DataType.Values.Array.WithUpdatedElement
com.wyu4.snowberryjam.Compiler.DataType.Tasks.ExecutableTask <|.. com.wyu4.snowberryjam.Compiler.DataType.Tasks.IfTask
@enduml